on: 
  workflow_dispatch:
  schedule:
    - cron: "0 */11 * * 1,3,5"
  
name: Reminders

jobs:
  Reminding:
    runs-on: macOS-latest
    env:
      MY_GITHUB_REPO: ${{ github.repository }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: jdtrat/actions/reminders@master
