on: 
  workflow_dispatch:
  schedule:
    - cron: "0 */11 * * 1,3,5"
  
name: Reminders

jobs:
  Reminding:
    runs-on: macOS-latest
    env:
      MY_GITHUB_REPO: ${{ github.repository }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      - name: Checkout Reminders Repo
        uses: actions/checkout@v2
        with:
          repository: jdtrat/actions
          path: reminders
      - name: Trigger Reminder
        run: |
          source("R/remind_collaborator.R")
        shell: Rscript {0}
